orders/urls.py
from django.urls import path
from .views import OrderListView, checkout, add_to_cart


app_name = 'product'

urlpatterns = [
    path('', OrderListView.as_view(),name='OrderList'),
    path('chekout', checkout,name='checkout'),
    path('add-to-cart', add_to_cart,name='add_to_cart'),

]

product/urls.py
from django.urls import path
from .views import ProductDetail, ProductList, add_review, BrandList, BrandDetail


app_name = 'product'

urlpatterns = [
    path('', ProductList.as_view(),name='product_list'),
    path('<slug:slug>', ProductDetail.as_view(),name='product_detail'),
    path('<slug:slug>/add-review', add_review,name='add_review'),
    path('brands/', BrandList.as_view(),name='brand_list'),
    path('brands/<slug:slug>', BrandDetail.as_view(),name='brand_detail'),
    
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products' )),
    path('orders/', include('orders.urls', namespace='orders' )),

]





if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils.translation import gettext as _
from django.utils.text import slugify
from django.utils import timezone

'''
Product Models
Aut : Chatouirabie@gmail.com

'''
FLAG_CHOICE = (
    ('N','Nouveau'),
    ('V','Produit Vedette'),
    ('P','Promo'),
)

class Product(models.Model):

    nom = models.CharField(_("Nom"),max_length=100)
    image = models.ImageField(_("Image"), upload_to='products')
    prix = models.FloatField(_("Prix"))
    sku = models.IntegerField(_("SKU"))
    subtitle = models.CharField(_("SousTitre"), max_length=350)
    description = models.TextField(_("Description"), max_length=30000)
    flag = models.CharField(_("Flag"), max_length=1,choices=FLAG_CHOICE)
    slug =  models.SlugField(_("Slug"), null=True,blank=True)
    brand =  models.ForeignKey("Brand", verbose_name=_("Brand"),related_name='productbrand', on_delete=models.SET_NULL, null=True,blank=True)
    tags= TaggableManager()

    def save(self, *args, **kwargs):
       self.slug = slugify(self.nom)
       super(Product, self).save(*args, **kwargs) # Call the real save() method
       

    class Meta:
        verbose_name = 'Produit'
        verbose_name_plural = 'Produits'

    def __str__(self):
        return self.nom
    
    def avg_rate(self):
        product_rev = self.productreview.all()
        l= len(product_rev)
        if l > 0 :
            rev_sum = 0
            for rate in product_rev :
                rev_sum += rate.rate
            return rev_sum / l
        else :
            return 0
        
    
class Brand(models.Model):
    nom = models.CharField(_("Nom"),max_length=50)
    image =  models.ImageField(_("Image"), upload_to='brand')
    slug = models.SlugField(_("Slug"))

    def save(self, *args, **kwargs):
       self.slug = slugify(self.nom)
       super(Brand, self).save(*args, **kwargs) # Call the real save() method

    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'

    def __str__(self):
        return self.nom

class ProductImages(models.Model):
    product =models.ForeignKey(Product, verbose_name=_("Product"), related_name='productimage',on_delete=models.CASCADE)
    image = models.ImageField(_("Image"), upload_to='product_Images')

    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'
    

    def __str__(self):
        return str(self.product)
    
class ProductReview(models.Model):
    user= models.ForeignKey(User, verbose_name=_("User"), related_name='reviewuser', on_delete=models.SET_NULL, null=True,blank=True)
    product = models.ForeignKey(Product, verbose_name=_("Product"), related_name='productreview', on_delete=models.CASCADE)
    rate =models.IntegerField(_("Rate"))
    review = models.TextField(_("Review"), max_length=1000)
    date = models.DateTimeField(_("Date"), default=timezone.now )
    
    class Meta:
        verbose_name = 'Product Review'
        verbose_name_plural = 'Product Reviews'

    def __str__(self):
        return str(self.product) 

product/forms.py
from django import forms
from .models import ProductReview



class ProductReviewForm(forms.ModelForm):
    
    class Meta:
        model = ProductReview
        fields = ["rate", "review"]
        

product/views.py
from django.shortcuts import render, redirect
from .models import *
from django.views.generic import ListView, DetailView
from .forms import ProductReviewForm

class ProductList(ListView):
    model = Product
    paginate_by = 50
    extra_context = {'all_prod': Product.objects.all().count()}
  

class ProductDetail(DetailView):
    model = Product
    
    def get_context_data(self, **kwargs):
        product = self.get_object()
        context = super().get_context_data(**kwargs)
        context["related_product"] = Product.objects.filter(brand=product.brand )[:10] #pour limiter le nombre des produits cible a 10
        return context
    
    
    
def add_review (request,slug):
    product =  Product.objects.get(slug=slug)
    if request.method == 'POST':
        form = ProductReviewForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user =  request.user
            myform.product = product
            myform.save()
    
    return redirect(f'/products/{product.slug}')
    
class BrandList(ListView):
    model = Brand
    paginate_by = 20
    extra_context = {'all_brand': Brand.objects.all().count()}
    

class BrandDetail(ListView):
    model = Product
    paginate_by = 50
    template_name = "product/brand_detail.html"
    
    
    def get_queryset(self):
        brand = Brand.objects.get(slug=self.kwargs['slug'])
        query = Product.objects.filter(brand=brand)
        return query
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["brand"] = Brand.objects.get(slug=self.kwargs['slug'])
        return context
    

  

product/templates/product/brand_detail.html
{% extends "base.html" %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'en/css/brand-single.css' %}">
{% endblock css %}
               
{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>{{object}}</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'products:brand_list' %}">Brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{brand}}</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================--> 
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand}}</h3></a>
            <ul>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star"></li>
                <li class="total">(163 ratings)</li>
            </ul>
            <p>({{brand.productbrand.all|length}} items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4">
                    {% for object in object_list  %}
                            <div class="col">
                                <div class="product-card">
                                    <div class="product-media">
                                        <div class="product-label">
                                            <label class="label-text new">{{object.flag}} </label>
                                        </div>
                                        <a class="product-image" href="product-video.html">
                                            <img src="{{object.image.url}}" alt="product">
                                        </a>
                                        <div class="product-widget">
                                            <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                            <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                        </div>
                                    </div>
                                    <div class="product-content">
                                        <div class="product-rating">
                                            <i class="{% if object.avg_rate > 0 %} active {% endif %} icofont-star"></i>
                                            <i class="{% if object.avg_rate > 1 %} active {% endif %} icofont-star"></i>
                                            <i class="{% if object.avg_rate > 2 %} active {% endif %} icofont-star"></i>
                                            <i class="{% if object.avg_rate > 3 %} active {% endif %} icofont-star"></i>
                                            <i class="{% if object.avg_rate > 4 %} active {% endif %} icofont-star"></i>
                                            <a href="#">{{object.productreview.all|length}}</a>
                                        </div>
                                        <h6 class="product-name">
                                            <a href="{%url 'products:product_detail' object.slug %}">{{object}}</a>
                                        </h6>
                                        <h6 class="product-price">
                                        
                                            <span>{{object.prix}}<small></small></span>
                                        </h6>
                                        <button class="product-add" title="Add to Cart">
                                            <i class="fas fa-shopping-basket"></i>
                                            <span>add</span>
                                        </button>
                                        <div class="product-action">
                                            <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                            <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                            <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing {%if brand.productbrand.all|length > 50  %} 50 of {{brand.productbrand.all|length}} Results {% else %} {{brand.productbrand.all|length}} Results {% endif %}</p>
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                            <i class="fas fa-long-arrow-alt-left"></i>
                                        </a>
                                    </li>  
                                    {% endif %}
                                
                                    <li class="page-item"><a class="page-link active" href="?page={{ page_obj.number }}">{{page_obj.number}}</a></li>
                                    {% if page_obj.next_page_number < page_obj.paginator.num_pages %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{page_obj.next_page_number}}</a></li>  
                                    {% endif %}
                                    
                                    
                                    {% if page_obj.has_next %}
                                    <li class="page-item">...</li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{page_obj.paginator.num_pages}}</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                            <i class="fas fa-long-arrow-alt-right"></i>
                                        </a>
                                    </li>  
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>    
            </div>    
        <!--=====================================
                    SHOP PART END
        =======================================-->
        


{% endblock body %}       

product/templates/product/brand_list.html
{% extends "base.html" %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'en/css/brand-list.css' %}">
{% endblock css %}
               
{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    <option value=".vegetables">vegetables</option>
                                    <option value=".fruits">fruits</option>
                                    <option value=".drinks">drinks</option>
                                    <option value=".fishes">fishes</option>
                                    <option value=".meats">meats</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                    {% for brand in object_list  %}
                    <div class="col all vegetables">
                        <div class="brand-wrap">
                            <div class="brand-media">
                                <img src="{{brand.image.url}}" alt="brand">
                                <div class="brand-overlay">
                                    <a href="{% url 'products:brand_detail' brand.slug %}"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="brand-meta">
                                <h4>{{brand}}</h4>
                                <p>({{brand.productbrand.all|length}} items)</p>
                            </div>
                        </div>
                    </div>                      
                    {% endfor %}

                    
 
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 20 of {{all_brand}} Results</p>
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                            <i class="fas fa-long-arrow-alt-left"></i>
                                        </a>
                                    </li>  
                                {% endif %}
                             
                                <li class="page-item"><a class="page-link active" href="?page={{ page_obj.number }}">{{page_obj.number}}</a></li>
                                {% if page_obj.next_page_number < page_obj.paginator.num_pages %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{page_obj.next_page_number}}</a></li>  
                                {% endif %}
                            
                                
                                {% if page_obj.has_next %}
                                    <li class="page-item">...</li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{page_obj.paginator.num_pages}}</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                            <i class="fas fa-long-arrow-alt-right"></i>
                                        </a>
                                    </li>  
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->


{%endblock%}